name: aml_command_sdk
channels:
  - anaconda
  - pytorch
  - conda-forge
dependencies:
  - python==3.10.4
  - pytorch==1.11.0
  - torchvision==0.12.0
  - pillow==9.0.1
  - tqdm==4.64.0
  - mlflow==1.26.0
  - yapf==0.31.0
  - pylint==2.12.2
  - mypy==0.910
  - pip:
    - azure-ai-ml==0.1.0b4