name: aml_command_sdk
channels:
  - anaconda
  - pytorch
  - conda-forge
dependencies:
  - python==3.10.9
  - pytorch==1.12.1
  - torchvision==0.15.2
  - mlflow==2.5.0
  - pillow==10.0.0
  - tqdm==4.65.0
  - yapf==0.33.0
  - pylint==2.17.4
