channels:
  - anaconda
  - pytorch
  - conda-forge
dependencies:
  - python==3.9.10
  - pytorch==1.11.0
  - torchvision==0.12.0
  - tqdm==4.64.0
  - mlflow==1.26.0
  - pip==21.2.4
  - pip:
      - azure-ml==0.0.1
      - azureml-mlflow==1.41.0
      - azureml-core==1.41.0