channels:
  - anaconda
  - pytorch
  - conda-forge
dependencies:
  - python==3.10.9
  - pytorch==1.12.1
  - torchvision==0.15.2
  - mlflow==2.5.0
  - tqdm==4.65.0
  - pip==23.2.1
  - pip:
      - azure-ai-ml==1.8.0
      - azureml-mlflow==1.52.0
